version: '3.7'
networks:
  redtetris_network:
    driver: bridge
    name: redtetris_network  # <-- This is the actual name Docker will use
services:
  server:
    build:
      context: ./server
      target: dev-stage
      #target: prod-stage
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    #environment:
    #  - SERVER_PORT:3000
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - redtetris_network
  client:
    build:
      context: ./client
      target: dev-stage
      #target: prod-stage
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    depends_on:
      - server
    ports:
      - "8010:8010" # same port in vite.config.js for development
      #- "443:443"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    command: npm run dev
    networks:
      - redtetris_network
